### ISSUE TITLE
how to use an other resolver?

### ISSUE THREAD

**Issue by andreasschulze** [fanf2/doh101#1]
Hello Tony,

the code in doh.lua assume the resolver is available at the DOH servers name.
How could I provide https://doh.example/ which use 127.0.0.1:53 as resolver?
(explicitly not doh.example:53)

Or did I misunderstand something?

Andreas

**Comment by fanf2** [comment]
Hmm, yes, the README needs some work...

The nginx config is designed to run on the same host as a recursive server which has different views on different IP addresses. In order to make the DoT and DoH views consistent with the Do53 views, the back-end IP address that it connects to on port 53 is the same as the front-end IP address that the client connected to on port 443 or 853. (Note it uses nginx variable `$server_addr` which is an IP address not a hostname.)

It might make sense to change `doh.lua` to use a configurable resolver IP address and have `set $resolver $server_addr` in the `nginx.conf` by default.

At the moment it's configured for my own use without concessions to other setups due to laziness by me :-) It is not an important point of the design.

**Comment by fanf2** [comment]
OK, I have made that change and I've updated the README to explain this more clearly.

Thanks for the feedback, and thanks for trying out `doh101`!
